import {useEffect,useMemo,useState} from 'react'
import {MapContainer,TileLayer,GeoJSON,CircleMarker,Polygon,useMap} from 'react-leaflet'
import {Map as MapIcon,ListOrdered,BookOpen,Search,Target,TreePine,Radar,ClipboardCheck,Users,Ruler,Leaf,Flag,MapPin,ShieldCheck} from 'lucide-react'
import {Site,Change,enrich,validate,COLORS,WEIGHTS,HIGH_PRIORITY_THRESHOLD,isGreen,contributors,evidence} from './lib/scoring'
type Tab='map'|'rank'|'change'|'actions'|'method'
type Rep={total:number;inside:number;rejected:number}
const Fly=({p}:{p?:[number,number]})=>{const m=useMap();useEffect(()=>{if(p)m.flyTo(p,12)},[p,m]);return null}
const WORLD:[number,number][]=[[-85,-180],[-85,180],[85,180],[85,-180]]
const Badge=({p}:{p:string})=><span className="text-[11px] font-medium text-white px-2.5 py-0.5 rounded-full" style={{background:COLORS[p]}}>{p}</span>
const Tag=({v}:{v:string})=><span className={`text-xs px-2 py-0.5 rounded-full ${v==='High'?'bg-red-100 text-red-700':v==='Medium'?'bg-amber-100 text-amber-700':'bg-emerald-100 text-emerald-700'}`}>{v}</span>
function Ring({v,c}:{v:number;c:string}){const r=34,L=2*Math.PI*r;return <svg width="84" height="84" viewBox="0 0 84 84"><circle cx="42" cy="42" r={r} fill="none" stroke="#e2e8f0" strokeWidth="8"/><circle cx="42" cy="42" r={r} fill="none" stroke={c} strokeWidth="8" strokeLinecap="round" strokeDasharray={`${L*v/100} ${L}`} transform="rotate(-90 42 42)"/><text x="42" y="47" textAnchor="middle" fontSize="20" fontWeight="700" fill="#0f172a">{v}</text></svg>}
export default function App(){
 const [sites,setSites]=useState<Site[]>([]);const [changes,setCh]=useState<Change[]>([]);const [boundary,setB]=useState<any>(null);const [rep,setRep]=useState<Rep>({total:0,inside:0,rejected:0})
 const [err,setErr]=useState('');const [loading,setL]=useState(true);const [sel,setSel]=useState<Site>();const [selC,setSelC]=useState<Change>();const [tab,setTab]=useState<Tab>('map')
 const [q,setQ]=useState('');const [f,setF]=useState({pri:'All',heat:'All',flood:'All',rec:'All',min:0});const [demo,setDemo]=useState(false)
 const [lay,setLay]=useState({sites:true,high:false,change:false,green:false,heat:false,flood:false})
 useEffect(()=>{(async()=>{try{
  const b=await (await fetch('/boundary.json')).json();setB(b);const ring:number[][]=b.features[0].geometry.coordinates[0]
  let raw:Site[];try{const r=await fetch('/api/sites');if(!r.ok)throw 0;raw=(await r.json()).map(enrich)}catch{raw=(await (await fetch('/sites.json')).json()).map(enrich)}
  const v=validate(raw,ring);setSites(v.ok);setRep(v.report)
  setCh(validate((await (await fetch('/changes.json')).json()) as Change[],ring).ok)}catch{setErr('Could not load data files. Check that public/sites.json, changes.json and boundary.json exist.')}finally{setL(false)}})()},[])
 const shown=useMemo(()=>sites.filter(s=>(f.pri==='All'||s.priority===f.pri)&&(f.heat==='All'||s.heat_risk===f.heat)&&(f.flood==='All'||s.flood_risk===f.flood)&&(f.rec==='All'||s.recommendation===f.rec)&&s.score!>=f.min&&(!q||[s.id,s.name,s.locality,s.recommendation,s.current_use].join(' ').toLowerCase().includes(q.toLowerCase()))),[sites,f,q])
 const ranked=useMemo(()=>[...shown].sort((a,b)=>b.score!-a.score!),[shown]);const top=useMemo(()=>[...sites].sort((a,b)=>b.score!-a.score!),[sites])
 const hp=shown.filter(s=>s.score!>=HIGH_PRIORITY_THRESHOLD);const filtered=shown.length!==sites.length
 // All KPIs derive from the same filtered set that the map, table and actions use.
 const kpi:[string,string|number,any][]=[['Candidate sites',shown.length,MapPin],['High priority sites',hp.length,Flag],['Potential area',(shown.reduce((a,s)=>a+s.area_sqm,0)/1e4).toFixed(1)+' ha',Ruler],['Potential beneficiaries',shown.reduce((a,s)=>a+s.population_nearby,0).toLocaleString(),Users],['Green intervention potential',(shown.filter(isGreen).reduce((a,s)=>a+s.area_sqm,0)/1e4).toFixed(1)+' ha',Leaf]]
 const pick=(s:Site)=>{setSel(s);setSelC(undefined);setTab('map')};const pickC=(c:Change)=>{setSelC(c);setSel(undefined);setLay(l=>({...l,change:true}));setTab('map')}
 const onSearch=(v:string)=>{setQ(v);const m=sites.find(s=>s.id.toLowerCase()===v.trim().toLowerCase());if(m)pick(m)}
 if(loading)return <div className="p-10 text-slate-300">Loading Jammu District data…</div>
 if(err)return <div className="p-10 text-red-300">{err}</div>
 const tabs:[Tab,string,any][]=[['map','Map',MapIcon],['rank','Priority sites',ListOrdered],['change','Change monitor',Radar],['actions','Recommended actions',ClipboardCheck],['method','Data & methodology',BookOpen]]
 const flyTo:[number,number]|undefined=sel?[sel.latitude,sel.longitude]:selC?[selC.latitude,selC.longitude]:undefined
 const dd=(k:'pri'|'heat'|'flood'|'rec',l:string,o:string[])=><select value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})} className="py-1.5 px-2.5 rounded-lg bg-white/95 text-slate-900 text-sm"><option value="All">{l}: all</option>{o.map(x=><option key={x}>{x}</option>)}</select>
 return <div className="min-h-screen text-slate-100">
  <header className="px-5 pt-4 pb-3 flex flex-wrap items-center gap-4 border-b border-white/10 backdrop-blur">
   <div className="flex items-center gap-3"><div className="bg-emerald-500 text-slate-900 rounded-xl p-2"><TreePine/></div><div><h1 className="text-xl font-bold tracking-tight">JAMMU RECLAIM AI</h1><p className="text-xs text-slate-400">Discover. Prioritise. Transform.</p></div></div>
   <div className="text-xs rounded-xl px-3 py-1.5 border border-emerald-400/40 bg-emerald-400/10 text-emerald-200"><b>STUDY REGION</b><br/>Jammu District, Jammu & Kashmir, India</div>
   <span className="text-[11px] px-2.5 py-1 rounded-full bg-amber-400/15 text-amber-200 border border-amber-300/30">Prototype · demonstration data</span>
   <nav className="flex gap-1 ml-auto flex-wrap bg-white/5 rounded-xl p-1">{tabs.map(([k,l,I])=><button key={k} onClick={()=>setTab(k)} className={`px-3 py-1.5 rounded-lg text-sm flex gap-1.5 items-center transition ${tab===k?'bg-emerald-500 text-slate-900 font-medium':'text-slate-300 hover:bg-white/10'}`}><I size={15}/>{l}</button>)}</nav>
  </header>
  <section className="px-4 pt-4"><div className="grid grid-cols-2 md:grid-cols-5 gap-3">{kpi.map(([l,v,I])=><div key={l} className="card p-3.5 border-l-4 border-emerald-500 flex items-center gap-3"><I className="text-emerald-600 shrink-0" size={22}/><div><div className="text-[11px] text-slate-500">{l}</div><div className="text-2xl font-bold leading-tight">{v}</div></div></div>)}</div>
   <p className="text-[11px] text-slate-400 mt-2">Figures cover {filtered?`${shown.length} of ${sites.length} sites matching current filters`:`all ${sites.length} candidate sites`}. High priority = score ≥ {HIGH_PRIORITY_THRESHOLD}. Beneficiaries = estimated residents within ~1 km (overlaps possible). Geographic validation: {rep.inside} of {rep.total} records inside Jammu District, {rep.rejected} rejected.</p></section>
  <div className="px-4 py-3 flex flex-wrap gap-2 items-center">
   <div className="relative"><Search size={14} className="absolute left-2.5 top-2.5 text-slate-400"/><input value={q} onChange={e=>onSearch(e.target.value)} placeholder="Search ID, locality, intervention" className="pl-8 pr-2 py-1.5 rounded-lg bg-white/95 text-slate-900 text-sm w-64"/></div>
   <div className="py-1.5 px-2.5 rounded-lg bg-slate-700 text-slate-200 text-sm">District: Jammu (fixed)</div>
   {dd('pri','Priority',['Critical','High','Moderate','Low'])}{dd('heat','Heat risk',['High','Medium','Low'])}{dd('flood','Flood risk',['High','Medium','Low'])}{dd('rec','Intervention',[...new Set(sites.map(s=>s.recommendation!))].sort())}
   <label className="text-xs text-slate-300">Min score {f.min}<input type="range" min={0} max={90} value={f.min} onChange={e=>setF({...f,min:+e.target.value})} className="ml-2 align-middle accent-emerald-500"/></label>
   <button onClick={()=>{setDemo(true);pick(top[0])}} className="ml-auto flex items-center gap-1.5 bg-amber-400 hover:bg-amber-300 transition text-slate-900 px-3.5 py-1.5 rounded-lg text-sm font-semibold"><Target size={15}/>Demo mode</button>
  </div>
  {demo&&<div className="px-4 pb-2 flex gap-2 flex-wrap">{top.slice(0,3).map((s,i)=><button key={s.id} onClick={()=>pick(s)} className="bg-white/10 hover:bg-white/20 rounded-lg px-3 py-1.5 text-sm">Demo {i+1}: {s.id} · {s.score}/100 · {s.recommendation}</button>)}</div>}
  {shown.length===0&&<p className="px-4 text-amber-300 text-sm">No sites match these filters. Clear a filter to see candidate sites.</p>}
  {tab==='map'&&<div className="grid lg:grid-cols-[1fr_390px] gap-4 px-4 pb-4">
   <div className="h-[600px] rounded-2xl overflow-hidden relative ring-1 ring-white/10">
    <MapContainer center={[32.75,74.8]} zoom={10} scrollWheelZoom>
     <TileLayer attribution="© OpenStreetMap contributors (basemap context only)" url="https://tile.openstreetmap.org/{z}/{x}/{y}.png"/>
     {boundary&&<Polygon positions={[WORLD,boundary.features[0].geometry.coordinates[0].map(([x,y]:number[])=>[y,x])]} pathOptions={{stroke:false,fillColor:'#0b1424',fillOpacity:.5}} interactive={false}/>}
     {boundary&&<GeoJSON data={boundary} style={{color:'#10b981',weight:3,fillColor:'#10b981',fillOpacity:.07}} interactive={false}/>}
     {lay.sites&&shown.map(s=><CircleMarker key={s.id} center={[s.latitude,s.longitude]} radius={sel?.id===s.id?11:7} pathOptions={{color:'#fff',weight:sel?.id===s.id?3:1,fillColor:COLORS[s.priority!],fillOpacity:.95}} eventHandlers={{click:()=>pick(s)}}/>)}
     {lay.high&&hp.map(s=><CircleMarker key={'h'+s.id} center={[s.latitude,s.longitude]} radius={13} pathOptions={{color:'#f59e0b',weight:2,fill:false}} interactive={false}/>)}
     {lay.green&&shown.filter(isGreen).map(s=><CircleMarker key={'g'+s.id} center={[s.latitude,s.longitude]} radius={16} pathOptions={{color:'#22c55e',fillColor:'#22c55e',fillOpacity:.25,weight:1}} interactive={false}/>)}
     {lay.heat&&shown.filter(s=>s.heat_risk==='High').map(s=><CircleMarker key={'t'+s.id} center={[s.latitude,s.longitude]} radius={18} pathOptions={{stroke:false,fillColor:'#f97316',fillOpacity:.3}} interactive={false}/>)}
     {lay.flood&&shown.filter(s=>s.flood_risk==='High').map(s=><CircleMarker key={'f'+s.id} center={[s.latitude,s.longitude]} radius={18} pathOptions={{stroke:false,fillColor:'#3b82f6',fillOpacity:.3}} interactive={false}/>)}
     {lay.change&&changes.map(c=><CircleMarker key={c.id} center={[c.latitude,c.longitude]} radius={selC?.id===c.id?11:8} pathOptions={{color:'#fff',weight:2,fillColor:'#dc2626',fillOpacity:1}} eventHandlers={{click:()=>pickC(c)}}/>)}
     <Fly p={flyTo}/></MapContainer>
    <div className="absolute top-2 right-2 z-[1000] bg-white/95 text-slate-900 rounded-xl p-2.5 text-xs shadow space-y-1"><b>Map layers</b>
     {([['sites','Candidate sites'],['high','High priority sites'],['change','Potential urban change'],['green','Green opportunity'],['heat','Heat risk (high)'],['flood','Flood risk (high)']] as [keyof typeof lay,string][]).map(([k,l])=><label key={k} className="flex gap-1.5 items-center"><input type="checkbox" checked={lay[k]} onChange={e=>setLay({...lay,[k]:e.target.checked})}/>{l}</label>)}
     <label className="flex gap-1.5 items-center text-slate-400"><input type="checkbox" disabled/>Existing green spaces (planned)</label></div>
    <div className="absolute bottom-2 left-2 z-[1000] bg-white/95 text-slate-900 rounded-xl p-2.5 text-xs shadow space-y-0.5"><b>Analysis boundary</b>
     <div><span className="inline-block w-5 border-t-[3px] border-emerald-500 align-middle mr-1"/>Jammu District</div>
     {Object.entries(COLORS).map(([k,c])=><div key={k}><span className="inline-block w-2.5 h-2.5 rounded-full mr-1.5" style={{background:c}}/>{k}{k==='Critical'||k==='High'?' priority':''}</div>)}
     <div><span className="inline-block w-2.5 h-2.5 rounded-full mr-1.5 bg-red-600"/>Change alert (potential)</div></div>
   </div>
   {selC?<ChangePanel c={selC}/>:<Detail s={sel}/>}</div>}
  {tab==='rank'&&<div className="px-4 pb-6 overflow-x-auto"><table className="w-full card text-sm overflow-hidden"><thead><tr className="text-left text-slate-500 bg-slate-50">{['Rank','Site','Locality','Area (m²)','Score','Population','Heat','Flood','Intervention','Priority'].map(h=><th key={h} className="p-2.5 font-medium">{h}</th>)}</tr></thead><tbody>
   {ranked.map((s,i)=><tr key={s.id} onClick={()=>pick(s)} className="border-t cursor-pointer hover:bg-emerald-50"><td className="p-2.5 text-slate-400">{i+1}</td><td className="font-medium">{s.id}</td><td>{s.locality}</td><td>{s.area_sqm.toLocaleString()}</td><td><div className="flex items-center gap-2"><b>{s.score}</b><div className="w-16 h-1.5 bg-slate-200 rounded"><div className="h-1.5 rounded" style={{width:s.score+'%',background:COLORS[s.priority!]}}/></div></div></td><td>{s.population_nearby.toLocaleString()}</td><td><Tag v={s.heat_risk}/></td><td><Tag v={s.flood_risk}/></td><td>{s.recommendation}</td><td><Badge p={s.priority!}/></td></tr>)}</tbody></table></div>}
  {tab==='change'&&<div className="px-4 pb-6 space-y-3"><div className="rounded-2xl bg-red-500/10 border border-red-400/30 text-red-100 p-3.5 text-sm"><b>Prototype Change-Detection Demonstration.</b> Alerts are simulated; satellite change detection is not yet connected. Imagery alone cannot establish legality: every alert is a <i>potential</i> change requiring field verification.</div>
   <div className="grid md:grid-cols-2 gap-3">{changes.map(c=><div key={c.id} className="card p-3.5 text-sm flex gap-3 items-center"><Pair level={c.change_level}/><div className="flex-1"><b>{c.id}</b> · near {c.locality}<br/>{c.change_type}<br/><span className="text-slate-500">{c.historical_year} → {c.current_year} · change {c.change_level} · ~{c.approx_area_sqm?.toLocaleString()} m² · {Math.round(c.confidence*100)}% confidence</span><br/><button onClick={()=>pickC(c)} className="text-emerald-700 underline text-xs">Show on map</button></div></div>)}</div></div>}
  {tab==='actions'&&<div className="px-4 pb-6 max-w-4xl space-y-3"><div className="card p-4 text-sm"><b>{hp.length} of {shown.length} sites</b> score ≥ {HIGH_PRIORITY_THRESHOLD} and require further assessment. Next step for each: field survey, then verification against municipal land records.</div>
   {ranked.slice(0,5).map((s,i)=><div key={s.id} onClick={()=>pick(s)} className="card p-4 text-sm cursor-pointer hover:ring-2 ring-emerald-400 flex gap-4 items-center"><Ring v={s.score!} c={COLORS[s.priority!]}/><div><b>{i===0?'TOP RECOMMENDATION · ':''}{s.id} near {s.locality}</b><br/>Recommended action: conduct field survey<br/>Potential intervention: {s.recommendation}<br/><span className="text-slate-500">Reason: {contributors(s).slice(0,3).map(c=>c.text).join(' + ')}</span></div></div>)}</div>}
  {tab==='method'&&<Method rep={rep}/>}
  <footer className="text-center text-xs text-slate-500 py-5">Turning Jammu District's underutilised spaces into high-impact urban assets · Prototype</footer></div>}
function Pair({level}:{level:string}){const n=level==='High'?5:3;return <svg width="120" height="52" viewBox="0 0 120 52" className="shrink-0 rounded">{[0,60].map(x=><g key={x}><rect x={x} y="0" width="56" height="52" fill="#86a97a"/>{[0,1,2,3,4].slice(0,x?n:1).map(i=><rect key={i} x={x+4+(i%3)*17} y={4+Math.floor(i/3)*24} width="14" height="20" fill="#6b7280"/>)}<text x={x+3} y="49" fontSize="8" fill="#fff">{x?'2026':'2022'}</text></g>)}</svg>}
function ChangePanel({c}:{c:Change}){return <aside className="card p-5 text-sm space-y-1.5 overflow-y-auto max-h-[600px]">
 <div className="text-red-600 font-semibold">CHANGE ALERT · {c.id}</div><div className="text-slate-500 flex items-center gap-1"><MapPin size={13}/>Near {c.locality}</div><div>Historical observation: {c.historical_year}<br/>Current observation: {c.current_year}</div>
 <Pair level={c.change_level}/><div>Change detected: <b>{c.change_level.toUpperCase()}</b> (~{c.approx_area_sqm?.toLocaleString()} m²)<br/>Change type: {c.change_type}<br/>Confidence: {Math.round(c.confidence*100)}%<br/>Status: <b>{c.status}</b></div>
 <p className="text-[11px] text-slate-500">Potential unauthorised change detected — field verification required. {c.data_status}. Flow: historical → current → change detection → authority verification.</p></aside>}
function Detail({s}:{s?:Site}){
 if(!s)return <aside className="card p-6 text-slate-500 text-sm">Select a site on the map to see its score, evidence, recommendation and before/after concept.</aside>
 const rows:[string,any][]=[['Area',s.area_sqm.toLocaleString()+' m²'],['Current use',s.current_use],['Population nearby',s.population_nearby.toLocaleString()],['Green cover',s.green_cover_percent+'%'],['Accessibility',s.accessibility+'/100'],['Nearest park',(s.distance_to_nearest_park_m/1000).toFixed(1)+' km']]
 return <aside className="card p-5 overflow-y-auto max-h-[600px] text-sm">
  <div className="flex items-center gap-3"><Ring v={s.score!} c={COLORS[s.priority!]}/><div><div className="text-xs text-slate-500">SITE {s.id} · near {s.locality}</div><div className="font-semibold">Urban Opportunity Score</div><Badge p={s.priority!}/> <Tag v={s.heat_risk}/><span className="text-[10px] text-slate-400"> heat</span> <Tag v={s.flood_risk}/><span className="text-[10px] text-slate-400"> flood</span></div></div>
  <dl className="grid grid-cols-2 gap-x-3 gap-y-1.5 my-3">{rows.map(([k,v])=><div key={k}><dt className="text-slate-500 text-xs">{k}</dt><dd>{v}</dd></div>)}</dl>
  <h4 className="font-semibold mb-1">Main score contributors</h4>{contributors(s).slice(0,5).map(c=><div key={c.key} className="mb-1"><div className="flex justify-between text-xs"><span>{c.text}</span><span className="text-slate-500">{c.pts.toFixed(1)}/{c.max.toFixed(0)}</span></div><div className="h-1.5 bg-slate-200 rounded"><div className="h-1.5 rounded bg-emerald-500" style={{width:c.pts/c.max*100+'%'}}/></div></div>)}
  <h4 className="font-semibold mt-3">Why this site?</h4><ul className="text-xs mb-2">{evidence(s).map(([ok,t])=><li key={t} className={ok?'':'text-slate-400'}>{ok?'✓':'–'} {t}</li>)}</ul>
  <div className="rounded-xl bg-emerald-50 border border-emerald-200 p-3"><h4 className="font-semibold">🌳 {s.recommendation} <span className="text-xs font-normal text-slate-500">(confidence {s.rec_confidence}%)</span></h4>
  <div className="text-[11px] text-slate-500">AI-assisted rule-based recommendation engine (no ML model)</div><ul className="list-disc ml-5 text-xs mt-1">{s.reasons?.map(r=><li key={r}>{r}</li>)}</ul></div>
  <div className="grid grid-cols-2 gap-2 my-2 text-xs"><div className="bg-stone-200 rounded-xl p-2.5"><b>Before</b><br/>{s.current_use} · low greenery · low public value</div><div className="bg-emerald-100 rounded-xl p-2.5"><b>After</b><br/>{s.recommendation} · greenery · walking/rest area{s.flood_risk!=='Low'?' · stormwater management':''}</div></div>
  <p className="text-[11px] text-slate-500">Conceptual planning recommendation — not an engineering design. Prototype estimate: ~{Math.round(s.area_sqm*.8).toLocaleString()} m² green area.</p>
  <div className="text-[11px] bg-amber-50 border border-amber-200 rounded-xl p-2.5 mt-2 flex gap-2"><ShieldCheck size={14} className="shrink-0 mt-0.5"/><span>Data status: {s.status} · Detection confidence: {Math.round(s.confidence*100)}% · {s.analysis_status} · {s.verification}. Potential underutilised site identified for prototype analysis.</span></div></aside>}
function Method({rep}:{rep:Rep}){const h='text-white text-base font-semibold mt-4';return <div className="px-4 pb-8 max-w-3xl text-sm text-slate-300 space-y-2">
 <h2 className="text-xl text-white font-bold">Data & methodology</h2>
 <h3 className={h}>Geographic scope</h3><p>All analysis is restricted to Jammu District, Jammu & Kashmir, India. Boundary: Census of India 2011 district polygon for Jammu (via DataMeet), simplified for display; it excludes Samba and other districts. Replace with the current official boundary when available. The basemap shows surroundings for context only; they are excluded from all sites, statistics, scoring and alerts.</p>
 <p>Validation: {rep.total} records checked by point-in-polygon, {rep.inside} inside, {rep.rejected} rejected. An earlier draft dataset was audited against this boundary: 8 of 42 sites fell outside and were replaced.</p>
 <h3 className={h}>How the demonstration data is built</h3><p>Sites are simulated, not detected from imagery. They are placed inside the boundary around real localities (approximate anchor points) and every attribute is derived from one urban-intensity value so the data is internally consistent: built-up index rises toward the urban core, green cover and vegetation index fall with it, heat risk follows built-up and green cover, flood risk follows distance to the approximate Tawi and Chenab corridors, and population is an estimate of residents within about 1 km. Locality names are the nearest anchor point and are approximate.</p>
 <h3 className={h}>How candidate sites would be identified at scale</h3><p>Satellite/GIS data → land-cover and open-space analysis → potential underutilised-space detection → remove unsuitable locations → accessibility, population and environment analysis → candidate urban sites.</p>
 <h3 className={h}>Opportunity score (0–100)</h3><p>{Object.entries(WEIGHTS).map(([k,v])=>`${k} ${Math.round(v*100)}%`).join(', ')}. Bands: 0–40 low, 41–60 moderate, 61–80 high, 81–100 critical. High priority = score ≥ {HIGH_PRIORITY_THRESHOLD}.</p>
 <h3 className={h}>KPIs</h3><p>All dashboard figures are computed from the sites currently shown. Potential area = sum of site areas. Beneficiaries = sum of nearby-population estimates (upper bound, catchments may overlap). Green intervention potential = area of sites whose recommendation includes a Pocket Park, Rain Garden, Urban Forest, Green Buffer or Green Corridor.</p>
 <h3 className={h}>Data sources</h3><ul className="list-disc ml-5"><li>🛰 Sentinel-2 / Landsat — planned integration</li><li>🗺 OpenStreetMap — basemap connected; roads, parks, schools, hospitals, water bodies planned (to be clipped to the district)</li><li>📍 Administrative boundary — Census 2011, connected</li><li>📊 Prototype site dataset — simulated</li></ul>
 <h3 className={h}>Limitations</h3><p>Candidate locations, population, risk levels, change alerts and impact estimates are demonstration data and require validation with official municipal records and field surveys before implementation. Change alerts are potential changes only, never confirmed unauthorised construction. Recommendations are rule-based, not machine learning.</p></div>}
